/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AraRouteImport } from './routes/ara'
import { Route as DisYazilarRouteImport } from './routes/dis-yazilar'
import { Route as EtkinliklerRouteImport } from './routes/etkinlikler'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnasayfaRouteImport } from './routes/admin.anasayfa'
import { Route as AdminArayuzRouteImport } from './routes/admin.arayuz'
import { Route as AdminAyarlarRouteImport } from './routes/admin.ayarlar'
import { Route as AdminBaglantilarRouteImport } from './routes/admin.baglantilar'
import { Route as AdminDislinklerRouteImport } from './routes/admin.dislinkler'
import { Route as AdminEtkinliklerRouteImport } from './routes/admin.etkinlikler'
import { Route as AdminKategorilerRouteImport } from './routes/admin.kategoriler'
import { Route as AdminKullanicilarRouteImport } from './routes/admin.kullanicilar'
import { Route as AdminMedyaRouteImport } from './routes/admin.medya'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminSayfalarRouteImport } from './routes/admin.sayfalar'
import { Route as AdminYazilarRouteImport } from './routes/admin.yazilar'
import { Route as EtiketSlugRouteImport } from './routes/etiket.$slug'
import { Route as HaberlerIndexRouteImport } from './routes/haberler.index'
import { Route as HaberlerSlugRouteImport } from './routes/haberler.$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as KaynaklarIndexRouteImport } from './routes/kaynaklar.index'
import { Route as KaynaklarKindRouteImport } from './routes/kaynaklar.$kind'
import { Route as SayfaSlugRouteImport } from './routes/sayfa.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AraRoute = AraRouteImport.update({
  id: '/ara',
  path: '/ara',
  getParentRoute: () => rootRouteImport,
} as any)
const DisYazilarRoute = DisYazilarRouteImport.update({
  id: '/dis-yazilar',
  path: '/dis-yazilar',
  getParentRoute: () => rootRouteImport,
} as any)
const EtkinliklerRoute = EtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnasayfaRoute = AdminAnasayfaRouteImport.update({
  id: '/anasayfa',
  path: '/anasayfa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArayuzRoute = AdminArayuzRouteImport.update({
  id: '/arayuz',
  path: '/arayuz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAyarlarRoute = AdminAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBaglantilarRoute = AdminBaglantilarRouteImport.update({
  id: '/baglantilar',
  path: '/baglantilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDislinklerRoute = AdminDislinklerRouteImport.update({
  id: '/dislinkler',
  path: '/dislinkler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtkinliklerRoute = AdminEtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKategorilerRoute = AdminKategorilerRouteImport.update({
  id: '/kategoriler',
  path: '/kategoriler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKullanicilarRoute = AdminKullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedyaRoute = AdminMedyaRouteImport.update({
  id: '/medya',
  path: '/medya',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSayfalarRoute = AdminSayfalarRouteImport.update({
  id: '/sayfalar',
  path: '/sayfalar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYazilarRoute = AdminYazilarRouteImport.update({
  id: '/yazilar',
  path: '/yazilar',
  getParentRoute: () => AdminRoute,
} as any)
const EtiketSlugRoute = EtiketSlugRouteImport.update({
  id: '/etiket/$slug',
  path: '/etiket/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerIndexRoute = HaberlerIndexRouteImport.update({
  id: '/haberler/',
  path: '/haberler/',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerSlugRoute = HaberlerSlugRouteImport.update({
  id: '/haberler/$slug',
  path: '/haberler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KaynaklarIndexRoute = KaynaklarIndexRouteImport.update({
  id: '/kaynaklar/',
  path: '/kaynaklar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaynaklarKindRoute = KaynaklarKindRouteImport.update({
  id: '/kaynaklar/$kind',
  path: '/kaynaklar/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const SayfaSlugRoute = SayfaSlugRouteImport.update({
  id: '/sayfa/$slug',
  path: '/sayfa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ara': typeof AraRoute
  '/dis-yazilar': typeof DisYazilarRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/giris': typeof GirisRoute
  '/admin/anasayfa': typeof AdminAnasayfaRoute
  '/admin/arayuz': typeof AdminArayuzRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/baglantilar': typeof AdminBaglantilarRoute
  '/admin/dislinkler': typeof AdminDislinklerRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sayfalar': typeof AdminSayfalarRoute
  '/admin/yazilar': typeof AdminYazilarRoute
  '/etiket/$slug': typeof EtiketSlugRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/kaynaklar/$kind': typeof KaynaklarKindRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/haberler/': typeof HaberlerIndexRoute
  '/kaynaklar/': typeof KaynaklarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ara': typeof AraRoute
  '/dis-yazilar': typeof DisYazilarRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/giris': typeof GirisRoute
  '/admin/anasayfa': typeof AdminAnasayfaRoute
  '/admin/arayuz': typeof AdminArayuzRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/baglantilar': typeof AdminBaglantilarRoute
  '/admin/dislinkler': typeof AdminDislinklerRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sayfalar': typeof AdminSayfalarRoute
  '/admin/yazilar': typeof AdminYazilarRoute
  '/etiket/$slug': typeof EtiketSlugRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/kaynaklar/$kind': typeof KaynaklarKindRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/haberler': typeof HaberlerIndexRoute
  '/kaynaklar': typeof KaynaklarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ara': typeof AraRoute
  '/dis-yazilar': typeof DisYazilarRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/giris': typeof GirisRoute
  '/admin/anasayfa': typeof AdminAnasayfaRoute
  '/admin/arayuz': typeof AdminArayuzRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/baglantilar': typeof AdminBaglantilarRoute
  '/admin/dislinkler': typeof AdminDislinklerRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sayfalar': typeof AdminSayfalarRoute
  '/admin/yazilar': typeof AdminYazilarRoute
  '/etiket/$slug': typeof EtiketSlugRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/kaynaklar/$kind': typeof KaynaklarKindRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/haberler/': typeof HaberlerIndexRoute
  '/kaynaklar/': typeof KaynaklarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ara'
    | '/dis-yazilar'
    | '/etkinlikler'
    | '/giris'
    | '/admin/anasayfa'
    | '/admin/arayuz'
    | '/admin/ayarlar'
    | '/admin/baglantilar'
    | '/admin/dislinkler'
    | '/admin/etkinlikler'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/medya'
    | '/admin/menu'
    | '/admin/sayfalar'
    | '/admin/yazilar'
    | '/etiket/$slug'
    | '/haberler/$slug'
    | '/kategori/$slug'
    | '/kaynaklar/$kind'
    | '/sayfa/$slug'
    | '/admin/'
    | '/haberler/'
    | '/kaynaklar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ara'
    | '/dis-yazilar'
    | '/etkinlikler'
    | '/giris'
    | '/admin/anasayfa'
    | '/admin/arayuz'
    | '/admin/ayarlar'
    | '/admin/baglantilar'
    | '/admin/dislinkler'
    | '/admin/etkinlikler'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/medya'
    | '/admin/menu'
    | '/admin/sayfalar'
    | '/admin/yazilar'
    | '/etiket/$slug'
    | '/haberler/$slug'
    | '/kategori/$slug'
    | '/kaynaklar/$kind'
    | '/sayfa/$slug'
    | '/admin'
    | '/haberler'
    | '/kaynaklar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ara'
    | '/dis-yazilar'
    | '/etkinlikler'
    | '/giris'
    | '/admin/anasayfa'
    | '/admin/arayuz'
    | '/admin/ayarlar'
    | '/admin/baglantilar'
    | '/admin/dislinkler'
    | '/admin/etkinlikler'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/medya'
    | '/admin/menu'
    | '/admin/sayfalar'
    | '/admin/yazilar'
    | '/etiket/$slug'
    | '/haberler/$slug'
    | '/kategori/$slug'
    | '/kaynaklar/$kind'
    | '/sayfa/$slug'
    | '/admin/'
    | '/haberler/'
    | '/kaynaklar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AraRoute: typeof AraRoute
  DisYazilarRoute: typeof DisYazilarRoute
  EtkinliklerRoute: typeof EtkinliklerRoute
  GirisRoute: typeof GirisRoute
  EtiketSlugRoute: typeof EtiketSlugRoute
  HaberlerSlugRoute: typeof HaberlerSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  KaynaklarKindRoute: typeof KaynaklarKindRoute
  SayfaSlugRoute: typeof SayfaSlugRoute
  HaberlerIndexRoute: typeof HaberlerIndexRoute
  KaynaklarIndexRoute: typeof KaynaklarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ara': {
      id: '/ara'
      path: '/ara'
      fullPath: '/ara'
      preLoaderRoute: typeof AraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dis-yazilar': {
      id: '/dis-yazilar'
      path: '/dis-yazilar'
      fullPath: '/dis-yazilar'
      preLoaderRoute: typeof DisYazilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etkinlikler': {
      id: '/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/etkinlikler'
      preLoaderRoute: typeof EtkinliklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anasayfa': {
      id: '/admin/anasayfa'
      path: '/anasayfa'
      fullPath: '/admin/anasayfa'
      preLoaderRoute: typeof AdminAnasayfaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arayuz': {
      id: '/admin/arayuz'
      path: '/arayuz'
      fullPath: '/admin/arayuz'
      preLoaderRoute: typeof AdminArayuzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ayarlar': {
      id: '/admin/ayarlar'
      path: '/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AdminAyarlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/baglantilar': {
      id: '/admin/baglantilar'
      path: '/baglantilar'
      fullPath: '/admin/baglantilar'
      preLoaderRoute: typeof AdminBaglantilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dislinkler': {
      id: '/admin/dislinkler'
      path: '/dislinkler'
      fullPath: '/admin/dislinkler'
      preLoaderRoute: typeof AdminDislinklerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etkinlikler': {
      id: '/admin/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/admin/etkinlikler'
      preLoaderRoute: typeof AdminEtkinliklerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kategoriler': {
      id: '/admin/kategoriler'
      path: '/kategoriler'
      fullPath: '/admin/kategoriler'
      preLoaderRoute: typeof AdminKategorilerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kullanicilar': {
      id: '/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AdminKullanicilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medya': {
      id: '/admin/medya'
      path: '/medya'
      fullPath: '/admin/medya'
      preLoaderRoute: typeof AdminMedyaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sayfalar': {
      id: '/admin/sayfalar'
      path: '/sayfalar'
      fullPath: '/admin/sayfalar'
      preLoaderRoute: typeof AdminSayfalarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/yazilar': {
      id: '/admin/yazilar'
      path: '/yazilar'
      fullPath: '/admin/yazilar'
      preLoaderRoute: typeof AdminYazilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/etiket/$slug': {
      id: '/etiket/$slug'
      path: '/etiket/$slug'
      fullPath: '/etiket/$slug'
      preLoaderRoute: typeof EtiketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler/': {
      id: '/haberler/'
      path: '/haberler'
      fullPath: '/haberler/'
      preLoaderRoute: typeof HaberlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler/$slug': {
      id: '/haberler/$slug'
      path: '/haberler/$slug'
      fullPath: '/haberler/$slug'
      preLoaderRoute: typeof HaberlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaynaklar/': {
      id: '/kaynaklar/'
      path: '/kaynaklar'
      fullPath: '/kaynaklar/'
      preLoaderRoute: typeof KaynaklarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaynaklar/$kind': {
      id: '/kaynaklar/$kind'
      path: '/kaynaklar/$kind'
      fullPath: '/kaynaklar/$kind'
      preLoaderRoute: typeof KaynaklarKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sayfa/$slug': {
      id: '/sayfa/$slug'
      path: '/sayfa/$slug'
      fullPath: '/sayfa/$slug'
      preLoaderRoute: typeof SayfaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnasayfaRoute: typeof AdminAnasayfaRoute
  AdminArayuzRoute: typeof AdminArayuzRoute
  AdminAyarlarRoute: typeof AdminAyarlarRoute
  AdminBaglantilarRoute: typeof AdminBaglantilarRoute
  AdminDislinklerRoute: typeof AdminDislinklerRoute
  AdminEtkinliklerRoute: typeof AdminEtkinliklerRoute
  AdminKategorilerRoute: typeof AdminKategorilerRoute
  AdminKullanicilarRoute: typeof AdminKullanicilarRoute
  AdminMedyaRoute: typeof AdminMedyaRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminSayfalarRoute: typeof AdminSayfalarRoute
  AdminYazilarRoute: typeof AdminYazilarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnasayfaRoute: AdminAnasayfaRoute,
  AdminArayuzRoute: AdminArayuzRoute,
  AdminAyarlarRoute: AdminAyarlarRoute,
  AdminBaglantilarRoute: AdminBaglantilarRoute,
  AdminDislinklerRoute: AdminDislinklerRoute,
  AdminEtkinliklerRoute: AdminEtkinliklerRoute,
  AdminKategorilerRoute: AdminKategorilerRoute,
  AdminKullanicilarRoute: AdminKullanicilarRoute,
  AdminMedyaRoute: AdminMedyaRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminSayfalarRoute: AdminSayfalarRoute,
  AdminYazilarRoute: AdminYazilarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AraRoute: AraRoute,
  DisYazilarRoute: DisYazilarRoute,
  EtkinliklerRoute: EtkinliklerRoute,
  GirisRoute: GirisRoute,
  EtiketSlugRoute: EtiketSlugRoute,
  HaberlerSlugRoute: HaberlerSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  KaynaklarKindRoute: KaynaklarKindRoute,
  SayfaSlugRoute: SayfaSlugRoute,
  HaberlerIndexRoute: HaberlerIndexRoute,
  KaynaklarIndexRoute: KaynaklarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
