/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DisYazilarRouteImport } from './routes/dis-yazilar'
import { Route as EtkinliklerRouteImport } from './routes/etkinlikler'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as KaynaklarRouteImport } from './routes/kaynaklar'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArayuzRouteImport } from './routes/admin.arayuz'
import { Route as AdminBaglantilarRouteImport } from './routes/admin.baglantilar'
import { Route as AdminDislinklerRouteImport } from './routes/admin.dislinkler'
import { Route as AdminEtkinliklerRouteImport } from './routes/admin.etkinlikler'
import { Route as AdminKullanicilarRouteImport } from './routes/admin.kullanicilar'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminSayfalarRouteImport } from './routes/admin.sayfalar'
import { Route as AdminYazilarRouteImport } from './routes/admin.yazilar'
import { Route as HaberlerIndexRouteImport } from './routes/haberler.index'
import { Route as HaberlerSlugRouteImport } from './routes/haberler.$slug'
import { Route as SayfaSlugRouteImport } from './routes/sayfa.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DisYazilarRoute = DisYazilarRouteImport.update({
  id: '/dis-yazilar',
  path: '/dis-yazilar',
  getParentRoute: () => rootRouteImport,
} as any)
const EtkinliklerRoute = EtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const KaynaklarRoute = KaynaklarRouteImport.update({
  id: '/kaynaklar',
  path: '/kaynaklar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArayuzRoute = AdminArayuzRouteImport.update({
  id: '/arayuz',
  path: '/arayuz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBaglantilarRoute = AdminBaglantilarRouteImport.update({
  id: '/baglantilar',
  path: '/baglantilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDislinklerRoute = AdminDislinklerRouteImport.update({
  id: '/dislinkler',
  path: '/dislinkler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtkinliklerRoute = AdminEtkinliklerRouteImport.update({
  id: '/etkinlikler',
  path: '/etkinlikler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKullanicilarRoute = AdminKullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSayfalarRoute = AdminSayfalarRouteImport.update({
  id: '/sayfalar',
  path: '/sayfalar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYazilarRoute = AdminYazilarRouteImport.update({
  id: '/yazilar',
  path: '/yazilar',
  getParentRoute: () => AdminRoute,
} as any)
const HaberlerIndexRoute = HaberlerIndexRouteImport.update({
  id: '/haberler/',
  path: '/haberler/',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerSlugRoute = HaberlerSlugRouteImport.update({
  id: '/haberler/$slug',
  path: '/haberler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SayfaSlugRoute = SayfaSlugRouteImport.update({
  id: '/sayfa/$slug',
  path: '/sayfa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dis-yazilar': typeof DisYazilarRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/giris': typeof GirisRoute
  '/kaynaklar': typeof KaynaklarRoute
  '/admin/arayuz': typeof AdminArayuzRoute
  '/admin/baglantilar': typeof AdminBaglantilarRoute
  '/admin/dislinkler': typeof AdminDislinklerRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sayfalar': typeof AdminSayfalarRoute
  '/admin/yazilar': typeof AdminYazilarRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/haberler/': typeof HaberlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dis-yazilar': typeof DisYazilarRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/giris': typeof GirisRoute
  '/kaynaklar': typeof KaynaklarRoute
  '/admin/arayuz': typeof AdminArayuzRoute
  '/admin/baglantilar': typeof AdminBaglantilarRoute
  '/admin/dislinkler': typeof AdminDislinklerRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sayfalar': typeof AdminSayfalarRoute
  '/admin/yazilar': typeof AdminYazilarRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/haberler': typeof HaberlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dis-yazilar': typeof DisYazilarRoute
  '/etkinlikler': typeof EtkinliklerRoute
  '/giris': typeof GirisRoute
  '/kaynaklar': typeof KaynaklarRoute
  '/admin/arayuz': typeof AdminArayuzRoute
  '/admin/baglantilar': typeof AdminBaglantilarRoute
  '/admin/dislinkler': typeof AdminDislinklerRoute
  '/admin/etkinlikler': typeof AdminEtkinliklerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sayfalar': typeof AdminSayfalarRoute
  '/admin/yazilar': typeof AdminYazilarRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/haberler/': typeof HaberlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dis-yazilar'
    | '/etkinlikler'
    | '/giris'
    | '/kaynaklar'
    | '/admin/arayuz'
    | '/admin/baglantilar'
    | '/admin/dislinkler'
    | '/admin/etkinlikler'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/sayfalar'
    | '/admin/yazilar'
    | '/haberler/$slug'
    | '/sayfa/$slug'
    | '/admin/'
    | '/haberler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dis-yazilar'
    | '/etkinlikler'
    | '/giris'
    | '/kaynaklar'
    | '/admin/arayuz'
    | '/admin/baglantilar'
    | '/admin/dislinkler'
    | '/admin/etkinlikler'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/sayfalar'
    | '/admin/yazilar'
    | '/haberler/$slug'
    | '/sayfa/$slug'
    | '/admin'
    | '/haberler'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dis-yazilar'
    | '/etkinlikler'
    | '/giris'
    | '/kaynaklar'
    | '/admin/arayuz'
    | '/admin/baglantilar'
    | '/admin/dislinkler'
    | '/admin/etkinlikler'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/sayfalar'
    | '/admin/yazilar'
    | '/haberler/$slug'
    | '/sayfa/$slug'
    | '/admin/'
    | '/haberler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DisYazilarRoute: typeof DisYazilarRoute
  EtkinliklerRoute: typeof EtkinliklerRoute
  GirisRoute: typeof GirisRoute
  KaynaklarRoute: typeof KaynaklarRoute
  HaberlerSlugRoute: typeof HaberlerSlugRoute
  SayfaSlugRoute: typeof SayfaSlugRoute
  HaberlerIndexRoute: typeof HaberlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dis-yazilar': {
      id: '/dis-yazilar'
      path: '/dis-yazilar'
      fullPath: '/dis-yazilar'
      preLoaderRoute: typeof DisYazilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etkinlikler': {
      id: '/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/etkinlikler'
      preLoaderRoute: typeof EtkinliklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaynaklar': {
      id: '/kaynaklar'
      path: '/kaynaklar'
      fullPath: '/kaynaklar'
      preLoaderRoute: typeof KaynaklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arayuz': {
      id: '/admin/arayuz'
      path: '/arayuz'
      fullPath: '/admin/arayuz'
      preLoaderRoute: typeof AdminArayuzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/baglantilar': {
      id: '/admin/baglantilar'
      path: '/baglantilar'
      fullPath: '/admin/baglantilar'
      preLoaderRoute: typeof AdminBaglantilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dislinkler': {
      id: '/admin/dislinkler'
      path: '/dislinkler'
      fullPath: '/admin/dislinkler'
      preLoaderRoute: typeof AdminDislinklerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etkinlikler': {
      id: '/admin/etkinlikler'
      path: '/etkinlikler'
      fullPath: '/admin/etkinlikler'
      preLoaderRoute: typeof AdminEtkinliklerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kullanicilar': {
      id: '/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AdminKullanicilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sayfalar': {
      id: '/admin/sayfalar'
      path: '/sayfalar'
      fullPath: '/admin/sayfalar'
      preLoaderRoute: typeof AdminSayfalarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/yazilar': {
      id: '/admin/yazilar'
      path: '/yazilar'
      fullPath: '/admin/yazilar'
      preLoaderRoute: typeof AdminYazilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/haberler/': {
      id: '/haberler/'
      path: '/haberler'
      fullPath: '/haberler/'
      preLoaderRoute: typeof HaberlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler/$slug': {
      id: '/haberler/$slug'
      path: '/haberler/$slug'
      fullPath: '/haberler/$slug'
      preLoaderRoute: typeof HaberlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sayfa/$slug': {
      id: '/sayfa/$slug'
      path: '/sayfa/$slug'
      fullPath: '/sayfa/$slug'
      preLoaderRoute: typeof SayfaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArayuzRoute: typeof AdminArayuzRoute
  AdminBaglantilarRoute: typeof AdminBaglantilarRoute
  AdminDislinklerRoute: typeof AdminDislinklerRoute
  AdminEtkinliklerRoute: typeof AdminEtkinliklerRoute
  AdminKullanicilarRoute: typeof AdminKullanicilarRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminSayfalarRoute: typeof AdminSayfalarRoute
  AdminYazilarRoute: typeof AdminYazilarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArayuzRoute: AdminArayuzRoute,
  AdminBaglantilarRoute: AdminBaglantilarRoute,
  AdminDislinklerRoute: AdminDislinklerRoute,
  AdminEtkinliklerRoute: AdminEtkinliklerRoute,
  AdminKullanicilarRoute: AdminKullanicilarRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminSayfalarRoute: AdminSayfalarRoute,
  AdminYazilarRoute: AdminYazilarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DisYazilarRoute: DisYazilarRoute,
  EtkinliklerRoute: EtkinliklerRoute,
  GirisRoute: GirisRoute,
  KaynaklarRoute: KaynaklarRoute,
  HaberlerSlugRoute: HaberlerSlugRoute,
  SayfaSlugRoute: SayfaSlugRoute,
  HaberlerIndexRoute: HaberlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
