-- Yazi kartlarinda gorunecek kapak gorseli.
-- Her yazinin icerigindeki ilk yerel gorsel kapak olarak atanir.
-- Zaten kapagi olan yazilara dokunulmaz.

UPDATE public.posts p
   SET cover_url = v.cover
  FROM (VALUES
    ('ilk-haber-acil-tibbin-ilklerinden-ismet-parlak-vefat-etti', '/wp-images/2025/02/GiruHlXWkAA2CZr-768x810.jpeg'),
    ('spontana-donus-ekgleri-post-arrest-ekg-ne-zaman-cekilmeli', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('turkiyede-acil-tip-anabilim-dali-kurulmasi-ve-gelisimi', '/wp-images/2025/02/Ekran-goruntusu-2025-02-10-121847.jpg'),
    ('resusitasyon-ve-kardiyak-arrest', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('aciltipuzmani-com-yayina-basladi', '/wp-images/2025/02/cropped-Acil-tip-logo-with-red-EKG-strip-removed.jpg'),
    ('vajinit', '/wp-images/2025/02/Ekran-goruntusu-2025-02-15-002320-1.jpg'),
    ('acil-serviste-yogun-bakim-yatisi-bekleyen-hastalarda-gorulen-komplikasyonlar', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('acilde-inatci-hickiriklar', '/wp-images/2025/02/f06c993e-2eff-4d7c-aabd-bdcbb4e86229.webp'),
    ('vajinal-dogum', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('hipernatremide-sivi-aciginin-hesaplanmasi', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('hipernatremi-acil-yaklasim', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('sok-ve-dolasim', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('su-cicegi-varisella-zoster', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('unstable-stabil-olmayan-angina-pektoris-usap', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('gogus-toraks-travmasina-genel-yaklasim', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('cerrahisiz-akut-apandisit', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('kan-gazi-analizi-akil-karti', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('yesil-idrar-nedenleri-ve-onemli-bilgiler', '/wp-images/2025/03/DALLE-2025-03-17-15.46.54-A-d.webp'),
    ('tehditkar-ortamlarda-112-mudahalesi', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('duyuru-asi-takviminde-guncelleme', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('kontrast-nefropatisi-icin-dusunceler', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('kisisel-koruyucu-ekipmanlari-kke-ile-resusitasyon', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('tibia-kirigi', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('hiperpotasemi-yanilgisi', '/wp-images/2025/02/Ekran-goruntusu-2025-02-07-185150-1.jpg'),
    ('torsades-de-pointes-tdp', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('femur-boyun-kiriklari', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('dissemine-intravaskuler-koagulasyon-dik', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('acilde-zor-havayolu-yonetimi', '/wp-images/2025/04/mallampati-1-300x300.webp'),
    ('acil-servis-klinik-tanitim-formu', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('sicaklik-hastaliginin-onlenmesi-ve-tedavisi-kilavuzu-wms-2024', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.png'),
    ('acil-tip-guncellemeleri-kardiyopulmoner-resusitasyonda-kullanilan-ilaclar', '/wp-images/2025/02/Adsiz-Tasarim-kopyasi.jpg'),
    ('kirim-kongo-kanamali-atesi-vaka-yonetim-rehberi-2025', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('p-dalgasi', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('cocukluk-donemi-asi-takvimi', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('ventrikuler-tasikardi-benzerleri', '/wp-images/2025/05/aciltipw.webp'),
    ('pulmoner-embolide-ekokardiyografi', '/wp-images/2025/05/acilcinetw.webp'),
    ('akut-epiglotit-acil-yaklasim', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('2025-acc-aha-acep-naemps-scai-koroner-sendromlu-hastalarin-yonetimine-yonelik-kilavuz-2', '/wp-images/2025/05/acilcinetw.webp'),
    ('kolanjit-belirsizligi', '/wp-images/2025/05/aciltipw.webp'),
    ('st-elevasyonu-ve-diger-nedenler', '/wp-images/2025/05/aciltipw.webp'),
    ('konsultasyon-orada-olmak-ya-da-olmamak-tum-mesele-bu', '/wp-images/2025/05/acilcinetw.webp'),
    ('periferik-ve-santral-siyanoz', '/wp-images/2025/07/bcceb7d3-8cf4-4180-bdf9-f8b534bb7b4b-300x300.webp'),
    ('kisa-kisa-travmada-guncel-yaklasimlar-bolum-2', '/wp-images/2025/05/acilcinetw.webp'),
    ('adrenalin-infuzyon-uygulama', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('kisa-kisa-travmada-guncel-yaklasimlar-bolum-9', '/wp-images/2025/05/acilcinetw.webp'),
    ('beyin-tomografisinde-gozden-kacanlar', '/wp-images/2025/05/aciltipw.webp'),
    ('takotsubo-kardiyomiyopatisi-stres-kardiyomiyopatisi', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('gecici-iskemik-atak-eve-gider-mi', '/wp-images/2025/05/aciltipw.webp'),
    ('karbonmonoksit-zehirlenmesi', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('2025-aha-kardiyopulmoner-resusitasyon-ve-acil-kardiovaskuler-bakim-kilavuzu-yayinlandi', '/wp-images/2025/10/Vol-152-No-16_suppl_2-Circulatio-225x300.webp'),
    ('yetiskin-ileri-yasam-destegi-2025-aha-kilavuzu-tam-metin-turkce', '/wp-images/2025/11/ilacdoz.webp'),
    ('karbonmonoksit-zehirlenmesi-2', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('karbonmonoksit-zehirlenmesi-2-2', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('solunum-ve-ventilasyonun-degerlendirilmesi-ve-yonetimi-atls-11-bolum-5', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('atls-11-bolum-6-dolasimin-degerlendirilmesi-ve-volum-resusitasyonu', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('e-bizi-doktor-gormeyecek-mi-acil-serviste-kadin-hekim-olmak', '/wp-images/2025/05/acilcinetw.webp'),
    ('kan-gazi-yorumlamada-klinik-senaryolar', '/wp-images/2025/05/acilcinetw.webp'),
    ('kan-gazi-yorumlamada-klinik-senaryolar-2', '/wp-images/2025/05/acilcinetw.webp'),
    ('acilde-vertigo-kabusu-kaostan-algoritmaya', '/wp-images/2025/05/acilcinetw.webp'),
    ('etomidate-ilac-kart', '/wp-images/2026/01/905ba913-e1fd-4a0e-b02c-caacc088b92f-200x300.webp'),
    ('yenidogana-ilk-dokunus', '/wp-images/2025/05/acilcinetw.webp'),
    ('metoklopramid-metpamid-ampul-uygulama-akil-karti', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('acil-serviste-gogus-agrisina-yaklasim-yuksek-duyarlilikli-troponin-protokolleri', '/wp-images/2025/05/aciltipw.webp'),
    ('2025-amerikan-kalp-dernegi-kardiyopulmoner-resusitasyon-ve-acil-kardiyovaskuler-bakim-kilavuzlari-bolum-8', '/wp-images/2025/05/acilcinetw.webp'),
    ('akut-arter-iskemisi', '/wp-images/2025/05/acilcinetw.webp'),
    ('batin-travmasina-acil-yaklasim', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('akut-arter-iskemisi-2', '/wp-images/2025/05/acilcinetw.webp'),
    ('acil-tipta-tanisi-zor-hastaliklar', '/wp-images/2025/05/aciltipw.webp'),
    ('gebelerde-travma-atls-2025-onerileri', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('dispepsi-yonetimi', '/wp-images/2025/05/acilcinetw.webp'),
    ('acil-tipta-en-guncel-bilgiler-2', '/wp-images/2025/05/aciltipw.webp'),
    ('ozefagus-varis-kanamasi', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('aha-acc-akut-pulmoner-emboli-pe-kilavuzu-onemli-degisiklikler-ve-yeni-siniflama', '/wp-images/2026/04/siniflamaresim.webp'),
    ('parasetamol-mu-asetaminofen-mi', '/wp-images/2026/04/Paracetamol-or-Acetaminophen_-.webp'),
    ('yeni-kilavuzlarda-asemptomatik-hipertansiyonun-ayaktan-yonetimi', '/wp-images/2026/05/tansiyonolcenhemsire-300x200.webp'),
    ('botulizm-acil-servis-yonetimi', '/wp-images/2025/05/acilcinetw.webp'),
    ('pediatrik-maske-yerlestirme-teknigi', '/wp-images/2025/05/Aacilcalisaniw.webp'),
    ('havayolu-yabanci-cisimleri-airway-foreign-bodies', '/wp-images/2026/06/24d40380-8eca-4869-b822-d24b3989c6ce.webp'),
    ('deneme-sayfasi-burada-calis', '/wp-images/2026/01/bp2.jpg')
  ) AS v(slug, cover)
 WHERE p.slug = v.slug
   AND p.cover_url IS NULL;
